"""invites_and_nullable_password

Revision ID: 97d5235160b5
Revises: ab401d6e8d49
Create Date: 2026-01-04 04:31:48.854170

"""

from alembic import op
import sqlalchemy as sa


revision = '97d5235160b5'
down_revision = 'ab401d6e8d49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_tokens_course_id'), 'invite_tokens', ['course_id'], unique=False)
    op.create_index(op.f('ix_invite_tokens_email'), 'invite_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_invite_tokens_expires_at'), 'invite_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_invite_tokens_organization_id'), 'invite_tokens', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invite_tokens_token_hash'), 'invite_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_invite_tokens_used_at'), 'invite_tokens', ['used_at'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_index(op.f('ix_invite_tokens_used_at'), table_name='invite_tokens')
    op.drop_index(op.f('ix_invite_tokens_token_hash'), table_name='invite_tokens')
    op.drop_index(op.f('ix_invite_tokens_organization_id'), table_name='invite_tokens')
    op.drop_index(op.f('ix_invite_tokens_expires_at'), table_name='invite_tokens')
    op.drop_index(op.f('ix_invite_tokens_email'), table_name='invite_tokens')
    op.drop_index(op.f('ix_invite_tokens_course_id'), table_name='invite_tokens')
    op.drop_table('invite_tokens')
    # ### end Alembic commands ###

