"""student_profile_and_roster_fields

Revision ID: a51bd2a0f2c4
Revises: 97d5235160b5
Create Date: 2026-01-04 04:41:23.317343

"""

from alembic import op
import sqlalchemy as sa


revision = 'a51bd2a0f2c4'
down_revision = '97d5235160b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('programme', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('course_memberships', sa.Column('student_number', sa.String(length=50), nullable=True))
    op.create_index(
        "uq_course_student_number",
        "course_memberships",
        ["course_id", "student_number"],
        unique=True,
        postgresql_where=sa.text("student_number IS NOT NULL"),
    )
    op.add_column('invite_tokens', sa.Column('full_name', sa.String(length=200), nullable=True))
    op.add_column('invite_tokens', sa.Column('student_number', sa.String(length=50), nullable=True))
    op.add_column('invite_tokens', sa.Column('programme', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_course_student_number", table_name="course_memberships")
    op.drop_column('invite_tokens', 'programme')
    op.drop_column('invite_tokens', 'student_number')
    op.drop_column('invite_tokens', 'full_name')
    op.drop_column('course_memberships', 'student_number')
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
