"""course_memberships

Revision ID: ab401d6e8d49
Revises: 0cc9cc576fd5
Create Date: 2026-01-04 04:20:44.444952

"""

from alembic import op
import sqlalchemy as sa


revision = 'ab401d6e8d49'
down_revision = '0cc9cc576fd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'co_lecturer', 'ta', 'student', name='course_role'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'user_id', name='uq_course_membership')
    )
    op.create_index(op.f('ix_course_memberships_course_id'), 'course_memberships', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_memberships_role'), 'course_memberships', ['role'], unique=False)
    op.create_index(op.f('ix_course_memberships_user_id'), 'course_memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_memberships_user_id'), table_name='course_memberships')
    op.drop_index(op.f('ix_course_memberships_role'), table_name='course_memberships')
    op.drop_index(op.f('ix_course_memberships_course_id'), table_name='course_memberships')
    op.drop_table('course_memberships')
    # ### end Alembic commands ###

